version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.19.9
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'cf2c95ecea9cf8fd4d87a5e379a81efd371e13a1'
      AUTHENTICATION_APIKEY_USERS: 'luke@chatfables.com'
    volumes:
      - /var/weaviate:/var/lib/weaviate
