services:
  - type: pserv
    name: weaviate
    env: docker
    autoDeploy: false
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.19.9
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
    volumes:
      - /var/weaviate:/var/lib/weaviate
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
